stages:
  - build
  - deploy




build_dev:
  stage: build
  image:
    name: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ''
  services:
    - docker:dind
  script:

    - export DOCKER_HOST=tcp://192.168.160.96:2375
    - docker info
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker build -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
#    - docker tag "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_IMAGE}:1.5"
#    - test ! -z "${CI_COMMIT_TAG}" && docker push "${CI_REGISTRY_IMAGE}:1.5"
  only:
     - dev
    
build_master:
  stage: build
  image:
    name: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ''
  services:
    - docker:dind
  script:

    - export DOCKER_HOST=tcp://192.168.160.96:2375
    - docker info
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker build -t "${CI_REGISTRY_IMAGE}:latest" .
    - docker tag "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
#    - test ! -z "${CI_COMMIT_TAG}" && docker push "${CI_REGISTRY_IMAGE}:1.5"
    - docker push "${CI_REGISTRY_IMAGE}:latest"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  only:
     - master  
    
    
deploy:
   stage: deploy
   variables:
      APP_NAME: production-chaufferie-front
      TYPE: production
   environment:
     name: production/${CI_COMMIT_REF_SLUG}
     url: http://192.168.160.74:31633/${TYPE}/Chaufferie

   image: roffe/kubectl:v1.13.0
   script:
      - kubectl delete --ignore-not-found=true secret gitlab-auth --kubeconfig="$admin" --namespace=gitlab-managed-apps
      - kubectl create secret docker-registry gitlab-auth --docker-server=$CI_REGISTRY --docker-username="$USER" --docker-password="$PASSWORD" --kubeconfig="$admin" --namespace=gitlab-managed-apps
      - cat k8s.yaml | envsubst | kubectl apply -f - --kubeconfig="$admin"
   only:
      - master
      
review:
  stage: deploy
  variables:
    APP_NAME: review-chaufferie-front
    TYPE: review
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    url: http://192.168.160.74:31633/${TYPE}/Chaufferie
    on_stop: stop_review

  image: roffe/kubectl:v1.13.0
  script:
      - kubectl delete --ignore-not-found=true secret gitlab-auth --kubeconfig="$admin" --namespace=gitlab-managed-apps
      - kubectl create secret docker-registry gitlab-auth --docker-server=$CI_REGISTRY --docker-username="$USER" --docker-password="$PASSWORD" --kubeconfig="$admin"   --namespace=gitlab-managed-apps
      - cat k8s.yaml | envsubst | kubectl apply -f - --kubeconfig="$admin"
  only:
    - dev
stop_review:
  stage: deploy
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  variables:
    APP_NAME: review-chaufferie-front
    TYPE: review
    GIT_STRATEGY: none
  image: roffe/kubectl:v1.13.0
  script:

    - kubectl delete service/${APP_NAME} --namespace=gitlab-managed-apps --kubeconfig="$admin"
    - kubectl delete deploy/${APP_NAME} --namespace=gitlab-managed-apps --kubeconfig="$admin"
    - kubectl delete ingress/${APP_NAME} --namespace=gitlab-managed-apps --kubeconfig="$admin"
  when: manual
  only:
    - dev
